CREATE TABLE Clients (
    Id UNIQUEIDENTIFIER NOT NULL PRIMARY KEY DEFAULT NEWID(),
    Name NVARCHAR(200) NOT NULL,
    ApiKey NVARCHAR(200) NOT NULL,
    CreatedAt DATETIME2 NOT NULL DEFAULT SYSUTCDATETIME()
);

CREATE TABLE Users (
    Id UNIQUEIDENTIFIER NOT NULL PRIMARY KEY DEFAULT NEWID(),
    UserName NVARCHAR(200) NOT NULL,
    FullName NVARCHAR(300) NULL,
    Email NVARCHAR(300) NULL,
    Mobile NVARCHAR(50) NULL,
    Language NVARCHAR(50) NULL,
    Culture NVARCHAR(50) NULL,
    PasswordHash NVARCHAR(MAX) NOT NULL,
    CreatedAt DATETIME2 NOT NULL DEFAULT SYSUTCDATETIME(),
    UpdatedAt DATETIME2 NULL
);

-- Example client (change before production)
INSERT INTO Clients (Name, ApiKey)
VALUES ('aljaz', 'testApiKey');
